import Head from 'next/head'
import styles from '../styles/Home.module.css'

import GroupAddIcon from '@mui/icons-material/GroupAdd';
import AddModeratorIcon from '@mui/icons-material/AddModerator';

import Header from './components/header'
import Particle from './components/particle_effect'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>XPLOx🍒 บอทตัวน้อยๆ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
      </Head>
      <Header />
      {/* <Particle /> */}

      {/* start --- sec 1 --- */}
      <div className={styles.sec_1}>
        <div className={styles.text__box}>
          <h1 className={styles.h1}>
            <span className={styles.text_1}>ยินดีตอนรับเข้าสู่บ้านของน้องนะคะ!</span>
            <span className={styles.text_2}>สามารถดูความสามารถของน้องได้ที่นี่เลยนะคะ!!</span>
            </h1>
          <div className={styles.xplox_prof}>
            <div className={styles.lines}></div>
            <div className={styles.imgBx}>
            <img src="/avatar.png" alt="XPLOx Profile Avatar" />
            </div>
          </div>
          <div className={styles.xplox_name}>XPLOx🍒 - น้องบอท</div>
          {/* <hr style={{width: "600px"}}/> */}
          <h3 className={styles.desc}>หนูชื่อ <span style={{
            color: "pink"
          }}>XPLOx</span> นะคะ ยินดีที่ได้รู้จักนะคะ <br/>
          หนูเป็นบอทที่สามารถสร้างความบรรเทิงหรือบรรเลงเพลงให้ทุกคนได้นะคะ <br/>
          หรือถ้าอยากจะรู้มากกว่านี้ว่ามีอะไรบ้าง สามารถเชิญหนูเข้าสู่เซิฟเวอร์ได้นะ!! 💕 </h3>
          {/* <hr style={{width: "350px"}}/> */}
          <div className={styles.xplox_btn}>
            <div className={styles.btn_invite}><a href="#"><GroupAddIcon/> เชิญน้องบอท</a></div>
            <div className={styles.btn_discord}><a href="#"><AddModeratorIcon/> เซิฟเวอร์ของน้อง</a></div>
          </div>
          {/* <div className={styles.skills_box}>
            <div className={styles.skill_tab}>
              <div className={styles.circle_red}></div>
              <div className={styles.circle_yellow}></div>
              <div className={styles.circle_green}></div>
            </div>
            <div className={styles.coding}>Skills : Reactjs , Nextjs , HTML/CSS (Basic) Working: Work from Home / Other</div>
          </div> */}
        </div>
      </div>
      {/* end --- sec 1 --- */}
    </div>
  )
}
